# Generated by Django 3.2.15 on 2022-11-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(choices=[('Corporate Headoffice', 'CORPORATE HEADOFFICE'), ('Operations Department', 'OPERATIONS DEPARTMENT'), ('Work station', 'WORK STATION'), ('Marketing Division', 'MARKETING DIVISION')], default='OPERATIONS DEPARTMENT', max_length=200)),
                ('Incident_Department', models.TextField()),
                ('Date_of_Incident', models.DateField()),
                ('Time_of_Incident', models.TimeField()),
                ('Incident_Location', models.TextField()),
                ('Initial_severity', models.CharField(choices=[('Mild', 'MILD'), ('Moderate', 'MODERATE'), ('Severe', 'SEVERE'), ('Fatal', 'FATAL')], default='MILD', max_length=70)),
                ('Suspected_Cause', models.TextField()),
                ('Immediate_Action_Taken', models.TextField()),
                ('Sub_Incident_Type', models.BooleanField(default=False, verbose_name=('Environmental Incident', 'Injury/Illness', 'Property Damage', 'Vehicle'))),
            ],
        ),
    ]
