# Generated by Django 3.2.15 on 2022-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportincident',
            name='Sub_Incident_Type',
        ),
        migrations.AddField(
            model_name='reportincident',
            name='Environmental_Incident',
            field=models.BooleanField(default=False, verbose_name='Vehicle'),
        ),
    ]
