# Generated by Django 3.2.15 on 2022-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20221122_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportincident',
            name='Injury',
            field=models.BooleanField(default=False, verbose_name='Injury/Illness'),
        ),
        migrations.AddField(
            model_name='reportincident',
            name='Property_Damage',
            field=models.BooleanField(default=False, verbose_name='Property Damage'),
        ),
        migrations.AddField(
            model_name='reportincident',
            name='Vehicle',
            field=models.BooleanField(default=False, verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='reportincident',
            name='Environmental_Incident',
            field=models.BooleanField(default=False, verbose_name='Environmental Incident'),
        ),
    ]
